--[[
	Entity - "the Hollow".

	A stalking AI with an explicit state machine and grid-accurate pathing. No
	PathfindingService and no baked navmesh: the maze is generated by us, so a BFS
	flow field is exact, costs about half a millisecond (measured in
	tools/test_maze.py), and cannot desync from the geometry.

	States
		dormant     never moves. Used for the round intro beat.
		patrol      drifts toward a deep tile, so the map is never safe.
		investigate walked to a noise, looks around, gives up.
		hunt        has you. Chases, with memory of the last confirmed position.
		feeding     mid-grab; deaf to everything else for a moment.

	Detection is generous about sound and strict about sight, which teaches the two
	rules the whole game runs on: move quietly, and never shine your beam at it.
]]

--[[ Shared modules live in ReplicatedStorage.Blacksite. Addressed through the service rather
     than script.Parent.Parent, because these folders are siblings, not ancestors. ]]
local shared = game:GetService("ReplicatedStorage"):WaitForChild("Blacksite")
local Config = require(shared:WaitForChild("Config"))
local Util = require(shared:WaitForChild("Util"))

local Entity = {}
Entity.__index = Entity

local cfg = Config.Entity
local COS_HALF_FOV = math.cos(math.rad(cfg.FaceAngle / 2))
local DecisionRate = 1 / 20 -- perception + routing; motion runs every Heartbeat

---------------------------------------------------------------------------
-- body
---------------------------------------------------------------------------

local BODY = {
	{ name = "Torso", size = Vector3.new(3.0, 5.4, 2.0), pos = Vector3.new(0, 5.6, 0) },
	{ name = "Head", size = Vector3.new(2.5, 2.7, 2.3), pos = Vector3.new(0, 9.5, 0), ball = true },
	{ name = "ArmL", size = Vector3.new(1.0, 4.4, 1.0), pos = Vector3.new(2.15, 6.2, 0), tilt = 6 },
	{ name = "ArmR", size = Vector3.new(1.0, 4.4, 1.0), pos = Vector3.new(-2.15, 6.2, 0), tilt = -6 },
	{ name = "HandL", size = Vector3.new(0.8, 2.8, 0.8), pos = Vector3.new(2.6, 3.0, 0), tilt = 11 },
	{ name = "HandR", size = Vector3.new(0.8, 2.8, 0.8), pos = Vector3.new(-2.6, 3.0, 0), tilt = -11 },
	{ name = "LegL", size = Vector3.new(1.15, 5.0, 1.15), pos = Vector3.new(0.95, 2.5, 0) },
	{ name = "LegR", size = Vector3.new(1.15, 5.0, 1.15), pos = Vector3.new(-0.95, 2.5, 0) },
	{ name = "Hip", size = Vector3.new(2.6, 1.2, 1.8), pos = Vector3.new(0, 2.9, 0) },
}

local GLOW = {
	{ name = "EyeL", size = Vector3.new(0.55, 0.55, 0.42), pos = Vector3.new(0.62, 9.95, -1.12), ball = true },
	{ name = "EyeR", size = Vector3.new(0.55, 0.55, 0.42), pos = Vector3.new(-0.62, 9.95, -1.12), ball = true },
	{ name = "Maw", size = Vector3.new(1.0, 0.22, 0.25), pos = Vector3.new(0, 8.75, -1.14) },
}

local function limb(spec, parent, material, color, transparency)
	local part = Instance.new("Part")
	part.Name = spec.name
	part.Anchored = true
	part.CanCollide = false
	part.CanQuery = false
	part.CanTouch = false
	part.Massless = true
	part.Size = spec.size
	part.CFrame = CFrame.new(spec.pos)
	if spec.tilt then
		part.CFrame = part.CFrame * CFrame.Angles(0, 0, math.rad(spec.tilt))
	end
	part.Material = material
	part.Color = color
	part.Transparency = transparency
	part.CastShadow = true
	part.TopSurface = Enum.SurfaceType.Smooth
	part.BottomSurface = Enum.SurfaceType.Smooth
	if spec.ball then
		part.Shape = Enum.PartType.Ball
	end
	part.Parent = parent
	return part
end

function Entity:buildModel()
	local model = Instance.new("Model")
	model.Name = "TheHollow"

	self.parts = {}
	for _, spec in ipairs(BODY) do
		local part = limb(spec, model, Enum.Material.Fabric, cfg.BodyColor, cfg.FadeTransparency)
		self.parts[#self.parts + 1] = part
	end

	self.head = self.parts[2]

	self.glowParts = {}
	for _, spec in ipairs(GLOW) do
		local part = limb(spec, model, Enum.Material.Neon, cfg.EyeColor, 0.12)
		part.CastShadow = false
		self.glowParts[#self.glowParts + 1] = part
	end

	self.eyeLight = Instance.new("PointLight")
	self.eyeLight.Range = 21
	self.eyeLight.Brightness = 0.65
	self.eyeLight.Color = cfg.EyeColor
	self.eyeLight.Shadows = false
	self.eyeLight.Parent = self.head

	self.highlight = Instance.new("Highlight")
	self.highlight.Name = "Reveal"
	self.highlight.Adornee = model
	self.highlight.FillTransparency = 1
	self.highlight.OutlineTransparency = 1
	self.highlight.FillColor = Color3.fromRGB(158, 250, 236)
	self.highlight.OutlineColor = Color3.fromRGB(196, 62, 52)
	self.highlight.Parent = model

	model.PrimaryPart = self.parts[1]
	return model
end

--- deps = { round, level, root }
function Entity.new(deps)
	local self = setmetatable({}, Entity)
	self.round = deps.round
	self.level = deps.level
	self.maze = deps.level.maze
	self.tile = deps.level.tile
	self.parts = {}
	self.model = self:buildModel()
	self.model.Parent = deps.root

	self.state = "dormant"
	self.closestDist = math.huge
	self.target = nil
	self.pos = Vector3.new(0, 0, 0)
	self.tx, self.ty = deps.level.maze.entryX, deps.level.maze.entryY
	self.dir = Vector3.new(0, 0, -1)
	self.speed = 0
	self.time = 0
	self.walkPhase = 0
	self.targetPlayer = nil
	self.lastSeen = -1000
	self.lastKnown = nil
	self.investigateTile = nil
	self.investigateUntil = 0
	self.nextAttack = 0
	self.repathIn = 0
	self.field = nil
	self.fieldKey = nil
	self.nextTile = nil
	self.patrolTile = nil
	self.feedingUntil = 0
	self.revealedUntil = 0
	self.idleTime = 0
	self.aggro = 0
	self.revealed = false

	self.model:SetAttribute("State", self.state)
	self.model:SetAttribute("Revealed", false)
	return self
end

function Entity:destroy()
	if self.model then
		self.model:Destroy()
		self.model = nil
	end
	self.field = nil
	self.parts = {}
end

---------------------------------------------------------------------------
-- geometry
---------------------------------------------------------------------------

function Entity:tileCenter(gx, gy)
	local x, z = self.maze:tileToWorld(gx, gy, self.tile)
	return Vector3.new(x, 0, z)
end

function Entity:setPositionFromTile(gx, gy)
	self.tx, self.ty = gx, gy
	self.pos = self:tileCenter(gx, gy)
	self.nextTile = nil
	self.field = nil
	self.repathIn = 0
	self:applyCFrame(0)
end

--- Yaw that points the model's front (-Z) along self.dir.
function Entity:yaw()
	local d = self.dir
	if d.X == 0 and d.Z == 0 then
		return 0
	end
	return math.atan2(d.X, d.Z) + math.pi
end

function Entity:applyCFrame(bob)
	local model = self.model
	if not model or not model.PrimaryPart or not model.Parent then
		return
	end
	local lean = 0
	if self.state == "hunt" then
		lean = 8
	elseif self.state == "feeding" then
		lean = 14
	elseif self.state == "investigate" then
		lean = 3
	end
	local cf = CFrame.new(self.pos + Vector3.new(0, 3.4 + (bob or 0), 0))
		* CFrame.Angles(0, self:yaw(), 0)
		* CFrame.Angles(math.rad(lean * 0.35), 0, math.rad(lean * 0.12))
	model:PivotTo(cf)
end

--- A walkable cell tile at least `minTiles` (Chebyshev) from every live player.
function Entity:pickFarTile(minTiles, avoidTile)
	local tiles = {}
	local maze = self.maze
	for gy = 1, maze.gridH, 2 do
		for gx = 1, maze.gridW, 2 do
			tiles[#tiles + 1] = { gx, gy }
		end
	end
	if #tiles == 0 then
		return maze.entryX, maze.entryY
	end

	local best, bestScore
	for _ = 1, 80 do
		local cand = tiles[math.random(#tiles)]
		local gx, gy = cand[1], cand[2]
		local minDist = math.huge
		local valid = true

		if avoidTile then
			if math.max(math.abs(avoidTile[1] - gx), math.abs(avoidTile[2] - gy)) < 8 then
				valid = false
			end
		end

		if valid then
			for _, st in self.round:eachPlayer() do
				if st.joined and st.alive and not st.escaped then
					local d = math.max(math.abs(st.tx - gx), math.abs(st.ty - gy))
					if d < minTiles then
						valid = false
						break
					end
					if d < minDist then
						minDist = d
					end
				end
			end
		end

		if valid and (bestScore == nil or minDist > bestScore) then
			best, bestScore = cand, minDist
		end
	end

	if best then
		return best[1], best[2]
	end
	local fallback = tiles[math.random(#tiles)]
	return fallback[1], fallback[2]
end

--- Snap onto the grid when a tile is entered. Keeps the AI's tile bookkeeping exact
--  (it is the same grid the player's position is read from) with no visible hitch.
function Entity:snapToTile(gx, gy)
	self.tx, self.ty = gx, gy
	self.pos = self:tileCenter(gx, gy)
end

---------------------------------------------------------------------------
-- perception
---------------------------------------------------------------------------

--- One pass over the live players: fills st.dist, st.seen, st.dread.
function Entity:scan()
	local now = self.time
	local radius = cfg.SightRange
	local best, bestScore
	self.closestDist = math.huge

	for player, st in self.round:eachPlayer() do
		st.seen = false
		st.dist = nil
		if st.joined and st.alive and not st.escaped and st.character and st.character.Parent then
			local to = st.pos - self.pos
			local flat = Vector3.new(to.X, 0, to.Z)
			local dist = flat.Magnitude
			st.dist = dist
			if dist < self.closestDist then
				self.closestDist = dist
			end

			local throughWall = dist < cfg.CloseSenseRange
			local clear = throughWall or self.maze:lineOfSight(self.tx, self.ty, st.tx, st.ty)

			if st.hiddenLock then
				-- Only a Hollow that is already hunting you, standing at the door,
				-- can pull you out. Otherwise you are simply not there.
				if self.state == "hunt" and self.targetPlayer == player and dist < cfg.KickRange then
					st.atDoor = true
				else
					st.atDoor = false
				end
			elseif clear then
				local facing = throughWall
				if not facing and dist > 0.01 then
					facing = self.dir:Dot(flat.Unit) > COS_HALF_FOV
				end
				-- Your beam is a searchlight. Catching sight of it means it sees you.
				local beamed = false
				if st.flashOn and st.look and dist < 120 and dist > 0.01 then
					beamed = st.look:Dot(-flat.Unit) > 0.9
				end
				if facing or beamed then
					st.seen = true
					st.atDoor = false
					if beamed then
						self.revealedUntil = now + cfg.RevealHold
						self.round:revealFlash(player)
					end
					local score = 1 - dist / radius + (beamed and 0.35 or 0)
					if score > (bestScore or -1) then
						best, bestScore = player, score
					end
				end
			else
				st.atDoor = false
			end
		end
	end

	return best
end

--- The single 0..1 number that drives the client's vignette, blur and shake.
function Entity:computeDread()
	local dreadBase = 0
	local closest = self.closestDist or math.huge
	if closest < math.huge then
		dreadBase = 1 - Util.clamp(closest / Config.Dread.Radius, 0, 1)
	end
	local stateWeight
	if self.state == "hunt" or self.state == "feeding" then
		stateWeight = Config.Dread.HuntMult
	elseif self.state == "investigate" then
		stateWeight = Config.Dread.InvestigateMult
	elseif self.state == "patrol" then
		stateWeight = Config.Dread.PatrolMult
	else
		stateWeight = 0.1
	end

	for player, st in self.round:eachPlayer() do
		local personal = 0
		if st.dist then
			personal = 1 - Util.clamp(st.dist / Config.Dread.Radius, 0, 1)
		end
		local dread = Util.clamp(personal * Config.Dread.ProximityFalloff + personal * 0.45 * stateWeight, 0, 1)
		if st.hiddenLock then
			dread = Util.clamp(dread + 0.3, 0, 1)
		end
		if self.state == "hunt" and self.targetPlayer == player then
			dread = 1
		end
		st.dread = dread
	end
end

function Entity:setState(nextState)
	if self.state == nextState then
		return
	end
	self.state = nextState
	if self.model then
		self.model:SetAttribute("State", nextState)
	end
end

--- A noise happened at `pos`. Loud enough and it is worth walking over to.
function Entity:hear(pos, radius)
	if self.state == "dormant" or self.state == "feeding" then
		return
	end
	if (pos - self.pos).Magnitude > radius then
		return
	end

	local gx, gy = self.level:tileOf(pos)
	gx, gy = self.round:nearestWalkable(self.maze, gx, gy)
	self.investigateTile = { gx, gy }
	self.investigateUntil = self.time + cfg.InvestigateTime
	if self.state ~= "hunt" then
		self:setState("investigate")
		self.field = nil
		self.nextTile = nil
		self.repathIn = 0
	end
end

---------------------------------------------------------------------------
-- brain
---------------------------------------------------------------------------

--- Called at DecisionRate: perception, state machine, routing.
function Entity:tick(dt)
	self.time = self.time + dt
	local now = self.time

	self:computeDread()

	if self.state == "dormant" then
		self:updateReveal(now)
		return
	end

	if self.state == "feeding" then
		if now >= self.feedingUntil then
			self:setState("patrol")
			self.targetPlayer = nil
			self.lastKnown = nil
			self.patrolTile = nil
		end
		self:updateReveal(now)
		return
	end

	local target = self:scan()

	if target then
		if self.targetPlayer ~= target then
			self:setState("hunt")
		end
		self.targetPlayer = target
		self.lastSeen = now
		local st = self.round.players[target]
		if st then
			self.lastKnown = { st.tx, st.ty }
		end
		self.investigateTile = nil
	elseif self.state == "hunt" then
		if now - self.lastSeen > cfg.SightMemory then
			self:setState("investigate")
			self.investigateUntil = now + cfg.InvestigateTime
			self.investigateTile = self.lastKnown
		end
	elseif self.state == "investigate" then
		if now > self.investigateUntil then
			self:setState("patrol")
			self.patrolTile = nil
		end
	end

	self:repositionIfStuck(dt, target)
	self:plan()
	self:attackCheck(now)
	self:updateReveal(now)
end

--- Rebuild the flow field at most once per RepathInterval, never per frame.
function Entity:plan()
	local goal = self:goalTile()
	self.goal = goal

	if goal == nil then
		self.field = nil
		self.fieldKey = nil
		self.nextTile = nil
		return
	end

	local key = goal[1] .. "_" .. goal[2]
	self.repathIn = self.repathIn - DecisionRate

	if self.field == nil or self.fieldKey ~= key or self.repathIn <= 0 then
		self.field = self.maze:flowField(goal[1], goal[2])
		self.fieldKey = key
		self.repathIn = cfg.RepathInterval

		if self.field == nil or self.field[self.ty] == nil or self.field[self.ty][self.tx] == nil then
			-- Unreachable: stop shuffling at a wall, go and look instead.
			if self.state == "hunt" then
				self:setState("investigate")
				self.investigateUntil = self.time + cfg.InvestigateTime
			end
			self.field = nil
			self.nextTile = nil
			return
		end

		self.nextTile = self:stepFrom(self.tx, self.ty)
	end
end

--- Called every Heartbeat so the body glides instead of stepping tile to tile.
function Entity:advance(dt)
	if not self.model or not self.model.PrimaryPart then
		return
	end

	if self.state == "dormant" or self.state == "feeding" then
		self.speed = 0
		self:applyCFrame(math.sin(self.time * 0.9) * 0.06)
		return
	end

	if self.field == nil or self.nextTile == nil then
		self.speed = Util.lerp(self.speed, 0, 0.35)
		self:applyCFrame(math.sin(self.time * 2.2) * 0.07)
		self:keepInside()
		return
	end

	self:stepTowards(self.nextTile, dt)
	self:keepInside()
end

--- Hunting without a route for a while is the worst outcome for tension, so it
--- relocates rather than pacing a corner forever.
function Entity:repositionIfStuck(dt, target)
	if self.state == "hunt" and not target and self.targetPlayer then
		local st = self.round.players[self.targetPlayer]
		if st and st.hiddenLock then
			self.idleTime = 0
			return
		end
		self.idleTime = self.idleTime + dt
		if self.idleTime > cfg.TeleportCooldown then
			self.idleTime = 0
			self:reposition(16)
		end
	else
		self.idleTime = 0
	end
end

function Entity:currentSpeed()
	return (cfg.Speeds[self.state] or cfg.Speeds.patrol) + self.aggro
end

--- Where it wants to be, as a grid tile.
function Entity:goalTile()
	if self.state == "hunt" then
		if self.targetPlayer then
			local st = self.round.players[self.targetPlayer]
			if st and st.seen and not st.hiddenLock then
				return { st.tx, st.ty }
			end
		end
		return self.lastKnown
	elseif self.state == "investigate" then
		if self.investigateTile then
			return self.investigateTile
		end
		return self.lastKnown
	end

	local tile = self.patrolTile
	if tile == nil or (self.tx == tile[1] and self.ty == tile[2]) then
		local gx, gy
		if self.round.gateOpen and math.random() < 0.6 then
			-- the airlock is the only way out, and it knows that
			gx, gy = self.maze.entryX + 1, self.maze.entryY
		else
			gx, gy = self:pickFarTile(cfg.PatrolPickRadius, { self.tx, self.ty })
		end
		self.patrolTile = { gx, gy }
		tile = self.patrolTile
	end
	return tile
end

--- Next tile downhill, plus a tile of corner-cutting where the geometry allows it.
function Entity:stepFrom(fromX, fromY)
	local maze, field = self.maze, self.field
	local nx, ny = maze:descend(field, fromX, fromY)
	if nx == nil then
		return nil
	end

	local lx, ly = maze:descend(field, nx, ny)
	if lx then
		local target = self:tileCenter(lx, ly)
		local flatX, flatZ = target.X - self.pos.X, target.Z - self.pos.Z
		local length = math.sqrt(flatX * flatX + flatZ * flatZ)
		local samples = math.max(2, math.floor(length / (self.tile * 0.45)))
		local clear = true
		for i = 1, samples do
			local t = i / samples
			local tgx, tgy = maze:worldToTile(self.pos.X + flatX * t, self.pos.Z + flatZ * t, self.tile)
			if maze:isSolid(tgx, tgy) then
				clear = false
				break
			end
		end
		if clear then
			return { lx, ly }
		end
	end
	return { nx, ny }
end

function Entity:stepTowards(tile, dt)
	local goal = self:tileCenter(tile[1], tile[2])
	local toX, toZ = goal.X - self.pos.X, goal.Z - self.pos.Z
	local dist = math.sqrt(toX * toX + toZ * toZ)

	if dist > 0.001 then
		self.dir = Vector3.new(toX, 0, toZ).Unit
	end

	local speed = self:currentSpeed()
	self.speed = speed
	local step = math.min(speed * dt, dist)
	self.pos = self.pos + self.dir * step
	self.walkPhase = self.walkPhase + dt * (speed * 0.42 + 1.4)

	if dist - step <= 0.55 then
		-- Snap on arrival: the AI's tile bookkeeping stays exact, and half a stud of
		-- correction is invisible at these speeds.
		self:snapToTile(tile[1], tile[2])
		self.nextTile = self:stepFrom(self.tx, self.ty)
		self.repathIn = math.max(self.repathIn, 0.06)
		if self.nextTile == nil then
			self.field = nil
			self.fieldKey = nil
		end
	end

	local bob
	if self.state == "hunt" then
		bob = math.sin(self.walkPhase * 1.9) * 0.42
	else
		bob = math.sin(self.walkPhase * 0.55) * 0.1
	end
	self:applyCFrame(bob)
end

function Entity:attackCheck(now)
	if now < self.nextAttack then
		return
	end
	for player, st in self.round:eachPlayer() do
		if st.joined and st.alive and not st.escaped and not st.hiddenLock and st.character and st.dist then
			if st.dist < cfg.ContactRange then
				self.nextAttack = now + cfg.AttackCooldown
				self.round:grab(player, st, self)
				return
			end
		end
	end
end

--- Being lit up costs you something: it turns solid *and* angry.
function Entity:updateReveal(now)
	local revealed = now < self.revealedUntil
	if revealed == self.revealed then
		return
	end
	self.revealed = revealed
	local transparency = revealed and cfg.RevealTransparency or cfg.FadeTransparency
	for _, part in ipairs(self.parts) do
		part.Transparency = transparency
	end
	for _, part in ipairs(self.glowParts) do
		part.Transparency = revealed and 0 or 0.12
	end
	self.eyeLight.Brightness = revealed and 1.5 or 0.65
	if self.model then
		self.model:SetAttribute("Revealed", revealed)
		self.model:SetAttribute("Alpha", transparency)
	end
end

--- It must never leave the playable grid, or a player could outrun it onto the dock.
function Entity:keepInside()
	local level = self.level
	local limitX = level.halfW - self.tile / 2
	local limitZ = level.halfH - self.tile / 2
	local x, z = self.pos.X, self.pos.Z
	local moved = false

	if x < -limitX then
		x, moved = -limitX, true
	elseif x > limitX then
		x, moved = limitX, true
	end
	if z < -limitZ then
		z, moved = -limitZ, true
	elseif z > limitZ then
		z, moved = limitZ, true
	end

	if moved then
		self.pos = Vector3.new(x, 0, z)
		local gx, gy = self.level:tileOf(self.pos)
		if self.maze:walkable(gx, gy) then
			self.tx, self.ty = gx, gy
		end
		self.field = nil
		self.nextTile = nil
		self.repathIn = 0
	end
end

--- Blink into a distant corridor: punishment for it standing around uselessly, and
--- the round-start beat that keeps it out of the players' face.
function Entity:reposition(minTiles)
	local gx, gy = self:pickFarTile(minTiles or 14, { self.tx, self.ty })
	self:setPositionFromTile(gx, gy)
	self.patrolTile = { gx, gy }
	self.goal = { gx, gy }
	self.round:scare(1.2, "blink")
end

function Entity:beginFeed()
	self:setState("feeding")
	self.feedingUntil = self.time + 1.7
	self.targetPlayer = nil
	self.lastKnown = nil
	self.investigateTile = nil
	self.field = nil
	self.fieldKey = nil
	self.nextTile = nil
	self.speed = 0
end

--- Settle back down once the round's dirty business is over.
function Entity:settle()
	self:setState("patrol")
	self.feedingUntil = 0
	self.nextAttack = 0
	self.idleTime = 0
	self.aggro = 0
end

--- The gate is open. Stop letting the team stroll up to it.
function Entity:enroll()
	self:setState("investigate")
	self.investigateTile = { self.maze.entryX + 1, self.maze.entryY }
	self.investigateUntil = self.time + 30
	self.aggro = self.aggro + 1.6
	self.patrolTile = nil
	self.field = nil
	self.fieldKey = nil
	self.nextTile = nil
end

return Entity
